### ISSUE TITLE
Use async/await in order to support Hapi  17

### ISSUE THREAD

**Issue by roux1max** [dixeed/hapi-starter-kit#3]
Change the promises-based code to an async/await code in order to migrate the project to Hapi 17.

**Comment by Nargonath** [comment]
I think we could lean towards https://github.com/hapipal/hpal for our hapi projects from now on. It enforces best practices from the community and has a CLI with an up to date boilerplate and also lots of nice things. However we'd have to migrate from using `Sequelize` as an ORM to `Objection`. It does not seem like a big deal though.
